<a href="https://colab.research.google.com/github/MSurenthar/Guvi_Task_2/blob/main/Numpy_tasks(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
print(np.zeros(10).size)
print(np.zeros(10).itemsize)

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
c = [1,2,0,0,4,0]
np.nonzero(c)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
np.random.random((3,3,3))

array([[[0.43503709, 0.62917589, 0.12467416],
        [0.042844  , 0.74538222, 0.62128981],
        [0.96228536, 0.92550266, 0.10047768]],

       [[0.28694421, 0.99187464, 0.79586488],
        [0.54014891, 0.68926613, 0.34472496],
        [0.99074826, 0.64846452, 0.79592617]],

       [[0.68329394, 0.82838967, 0.65138374],
        [0.94948598, 0.27952938, 0.32630404],
        [0.24630614, 0.40996732, 0.27430089]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
a = np.random.random((10,10))
print(a.min())
print(a.max())

0.006283802668906158
0.992263287618246


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
a = np.random.random(30)
a.mean()

0.524178042916988

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
a = np.ones((5,5))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
np.pad(a,pad_width=1,mode="constant",constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan

nan

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

False

In [ ]:
np.nan - np.nan

nan

In [ ]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
a = np.ones((8,8))
a[1::2,::2] = 0
a[::2,1::2] = 0
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
np.unravel_index(indices=100,shape=(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
np.tile(np.array([[1,0],[0,1]]),(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.random((5,5))
((x - x.min())/(x.max() - x.min()) )

array([[0.41107944, 0.90571133, 0.72768013, 0.95019037, 0.60620101],
       [0.24585925, 0.40632282, 0.62390821, 0.68572436, 0.69510416],
       [0.28816288, 0.30886226, 0.53057913, 0.52845722, 0.90970705],
       [0.31613936, 0.10160352, 1.        , 0.91062702, 0.64876911],
       [0.43472348, 0.34743735, 0.53397366, 0.15368453, 0.        ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
RGBA = np.dtype([('Red',np.uint8),('Green',np.uint8),('Blue',np.uint8),('Alpha',np.uint8)])
color = np.array((111,140,420,300),dtype = RGBA)
print(color['Red'])
type(color)

111


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
np.dot(np.ones((5,3)),np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
z=np.arange(11)
print(z)
z[(3<z)&(z<8)] *= -1
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))

print(np.sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z=np.arange(3)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print((Z<Z>Z))

[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
s = np.random.uniform(-1,1,5)
# print(np.copysign(s,+1))
np.ceil(s)
# np.abs(s)

array([-0.,  1.,  1., -0.,  1.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a = np.arange(1,6)
b = np.arange(4,10)
print(np.intersect1d(a,b))

[4 5]


31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
print(np.seterr())
print(np.errstate())

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
ystrd = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",ystrd)
tdy = np.datetime64('today', 'D')
print("Today: ",tdy)
tmrw  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tmrw)

Yestraday:  2022-05-10
Today:  2022-05-11
Tomorrow:  2022-05-12


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.multiply((np.add(A,B)) , (np.divide((np.negative(A)),2)))

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
a = np.linspace(1,2,10)
print(a)
print(a - a%1)
print(np.floor(a))
print(np.ceil(a))
print(a.astype(int))
print(np.trunc(a))

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 2.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 2.]
[1. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[1 1 1 1 1 1 1 1 1 2]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
print(np.tile(np.arange(0,5),(5,1)))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generator():
  for i in range(10):
        yield i
np.fromiter(generator(),dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
a = np.random.randint(10,50,size=10)
a.sort()
a

array([11, 19, 20, 25, 28, 34, 40, 44, 44, 48])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
np.add.reduce(np.arange(8).reshape((2,2,2)),0)

array([[ 4,  6],
       [ 8, 10]])

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A=np.random.randint(1,10,5)
B=np.random.randint(1,10,5)
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
z=np.arange(0,10)
print(z)
z.flags.writeable=False
z[2]=100
z

[0 1 2 3 4 5 6 7 8 9]


ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
a=np.random.random((10,2))
x,y=a[:,0], a[:,1]      #To convert from Cartesian Coordinates (x,y) to Polar Coordinates (r,θ):
rad=np.sqrt(x**2+y**2)  #r = √ ( x2 + y2 )
deg=np.arctan2(y,x)     #θ = tan-1 ( y / x )
print(rad)
print(deg)

[1.01620198 0.20287854 0.526603   0.78032692 0.40718461 0.90151324
 0.64588273 0.46204642 0.77706469 0.56830774]
[1.33318192 0.32070305 1.39223466 0.30512939 0.69977418 0.6225431
 0.68897223 1.42101628 1.40672536 1.0659734 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
m=np.random.randint(0,100,10)
print(m)
m[m.argmax()]=0
m

[88 17 15 11 91 51 29 15 44 58]


array([88, 17, 15, 11,  0, 51, 29, 15, 44, 58])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
Z['x'],Z['y']=np.meshgrid(0,1)
print(Z)

[[(0., 1.) (0., 1.) (0., 1.) (0., 1.) (0., 1.)]
 [(0., 1.) (0., 1.) (0., 1.) (0., 1.) (0., 1.)]
 [(0., 1.) (0., 1.) (0., 1.) (0., 1.) (0., 1.)]
 [(0., 1.) (0., 1.) (0., 1.) (0., 1.) (0., 1.)]
 [(0., 1.) (0., 1.) (0., 1.) (0., 1.) (0., 1.)]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.arange(1,5).reshape(2,2)
print(X)
Y = np.arange(5,9).reshape(2,2)
print(Y)
C = (1/(np.subtract.outer(X,Y)))
C

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[[[-0.25      , -0.2       ],
         [-0.16666667, -0.14285714]],

        [[-0.33333333, -0.25      ],
         [-0.2       , -0.16666667]]],


       [[[-0.5       , -0.33333333],
         [-0.25      , -0.2       ]],

        [[-1.        , -0.5       ],
         [-0.33333333, -0.25      ]]]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for itype in [np.int8,np.int16, np.int32, np.int64,]:
   print(np.iinfo(itype).min, (np.iinfo(itype).max))
for ftype in [np.float16,np.float32, np.float64, np.float128]:
   print(np.finfo(ftype).min, (np.finfo(ftype).max), (np.finfo(ftype).eps))

-128 127
-32768 32767
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-65500.0 65500.0 0.000977
-3.4028235e+38 3.4028235e+38 1.1920929e-07
-1.7976931348623157e+308 1.7976931348623157e+308 2.220446049250313e-16
-1.189731495357231765e+4932 1.189731495357231765e+4932 1.084202172485504434e-19


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(precision=2)
C

array([[[[-0.25, -0.2 ],
         [-0.17, -0.14]],

        [[-0.33, -0.25],
         [-0.2 , -0.17]]],


       [[[-0.5 , -0.33],
         [-0.25, -0.2 ]],

        [[-1.  , -0.5 ],
         [-0.33, -0.25]]]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
c=np.arange(1,100)
print(c)
d=np.random.uniform(0,100)
print(d)
index=(np.abs(c-d)).argmin()
print(index)
print(c[index])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
89.7324560534457
89
90


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
np.ones(10,[('position',[('x',float,1),
                            ('y',float,1)]),
               ('color',[('r',float,1),
                         ('g',float,1),
                         ('b',float,1)])])

/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py:204: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = empty(shape, dtype, order)


array([((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
rv=np.random.random((100,2))
x,y=np.atleast_2d(rv[:,0],rv[:,1])
d=np.sqrt((x-x.T)**2 +(y-y.T)**2)
print(d)

[[0.   0.67 0.47 ... 0.82 0.24 0.53]
 [0.67 0.   0.27 ... 0.42 0.59 0.85]
 [0.47 0.27 0.   ... 0.37 0.34 0.58]
 ...
 [0.82 0.42 0.37 ... 0.   0.63 0.72]
 [0.24 0.59 0.34 ... 0.63 0.   0.34]
 [0.53 0.85 0.58 ... 0.72 0.34 0.  ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
a=np.arange(5, dtype=np.float32)
b=a.astype(np.int32,copy=False)
print(a)
print(b)

[0. 1. 2. 3. 4.]
[0 1 2 3 4]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
fe=StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
z=np.genfromtxt(fe, delimiter=",", dtype=int)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
s=np.arange(4).reshape(2,2)
for index,value in np.ndenumerate(s):
    print(index, value)
for index in np.ndindex(s.shape):
    print(index, s[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x,y=np.meshgrid(np.linspace(0,1,3), np.linspace(0,1,3))
d=np.sqrt(x*x+y*y)
sigma,mu=1.0, 0.0
g=np.exp(-((d-mu)**2/(2.0*sigma**2)))
print(g)

[[1.   0.88 0.61]
 [0.88 0.78 0.54]
 [0.61 0.54 0.37]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n=2
p=3
z=np.zeros((n,n))
np.put(z,np.random.choice(range(n*n), p, replace=False),1)
print(z)

[[1. 1.]
 [1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x=np.random.rand(2,2)
x-x.mean(axis=1, keepdims=True)

array([[ 0.01, -0.01],
       [ 0.24, -0.24]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
print(x)
print(x[x[:,1].argsort()])

[[0.98 0.96]
 [0.84 0.36]]
[[0.84 0.36]
 [0.98 0.96]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
Z=np.zeros(4).reshape(2,2)
print(Z)
print((~Z.any(axis=0)).any())
X=np.ones(4).reshape(2,2)
print(X)
print((~X.any(axis=0)).any())

[[0. 0.]
 [0. 0.]]
True
[[1. 1.]
 [1. 1.]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
A=np.random.uniform(2,5,10)
a=0.5
b=A.flat[np.abs(A-a).argmin()]
print(b)

2.160258640907286


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A=np.arange(3).reshape(3,1)
B=np.arange(3).reshape(1,3)
it=np.nditer([A,B,None])
for x,y,z in it:z[...]=x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class Array(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
z= Array(np.arange(10), "range_10")
print(z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
a=np.ones(10)
b=np.random.randint(0,len(a),10)
a+=np.bincount(b,minlength=len(a))
print(a)
np.add.at(a,b,1)
print(a)

[1. 1. 4. 4. 2. 2. 2. 1. 1. 2.]
[1. 1. 7. 7. 3. 3. 3. 1. 1. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
a=[2,4,6,8,10,12]
b=[1,3,5,7,9,11]
np.bincount(b,a)

array([ 0.,  2.,  0.,  4.,  0.,  6.,  0.,  8.,  0., 10.,  0., 12.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h=16,16
i=np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
f=i[...,0]*(256*256)+i[...,1]*256+i[...,2]
n=len(np.unique(f))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.sum(axis=(-2,-1))
print(sum)
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[67 37 68 57]
 [45 42 56 53]
 [63 55 59 68]]
[[67 37 68 57]
 [45 42 56 53]
 [63 55 59 68]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D=np.random.uniform(0,1,100)
S=np.random.randint(1,10,100)
D_sums=np.bincount(S, weights=D)
D_counts=np.bincount(S)
D_means=D_sums/D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[ nan 0.49 0.4  0.52 0.49 0.72 0.56 0.35 0.32 0.42]
1    0.487146
2    0.401210
3    0.521507
4    0.493057
5    0.719983
6    0.556837
7    0.347099
8    0.315368
9    0.417898
dtype: float64


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
a=np.random.uniform(0,1,(2,2))
b=np.random.uniform(0,1,(2,2))
np.diag(np.dot(a,b))

array([0.85, 0.51])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
vec=np.array([1,2,3,4,5])
n=3
Z=np.zeros(len(vec)+(len(vec)-1)*(n))
Z[::n+1]=vec
print(Z)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A=5*np.ones((5,5,3))
B=1+np.ones((5,5))
print(A*B[:,:,None])

[[[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
A=np.arange(9).reshape(3,3)
A[[0,1]]=A[[1,0]]
print(A)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces=np.random.randint(0,100,(10,3))
f=np.roll(faces.repeat(2,axis=1),-1,axis=1)
f=f.reshape(len(f)*3,2)
F=np.sort(f,axis=1)
g=f.view(dtype=[('p0',f.dtype),('p1',f.dtype)] )
g=np.unique(g)
print(g)

[( 8, 82) (11, 91) (16, 23) (18, 33) (20, 39) (21, 47) (23, 81) (33, 60)
 (39, 78) (44,  8) (47, 68) (58, 87) (60, 18) (62, 66) (62, 81) (66, 93)
 (68, 21) (69, 58) (69, 87) (78, 20) (81, 16) (81, 93) (82, 44) (87, 69)
 (87, 94) (91, 97) (93, 62) (94, 69) (97, 11)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
a=np.bincount([1,3,5,7,9,2,4])
b=np.repeat(np.arange(len(a)),a)
print(b)

[1 2 3 4 5 7 9]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a,n=3) :
    ret=np.cumsum(a, dtype=float)
    ret[n:]=ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a=np.arange(20)
moving_average(a)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape=(a.size - window + 1, window)
    strides=(a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z=rolling(np.arange(9), 5)
print(Z)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
a=np.random.randint(0,1,20)
print(np.logical_not(a,out=a))
print(np.negative(a, out=a))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0,P1,p):
    t=P1 - P0
    l=(t**2).sum(axis=1)
    u=-((P0[:,0]-p[...,0])*t[:,0] + (P0[:,1]-p[...,1])*t[:,1]) / l
    u=u.reshape(len(u),1)
    d=P0+u*t-p
    return np.sqrt((d**2).sum(axis=1))
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,( 1,2))
distance(P0, P1, p)

array([ 7.65,  6.38, 17.11, 17.83,  0.37, 10.86,  9.97,  4.23,  0.28,
        4.58])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 7.65  6.38 17.11 17.83  0.37 10.86  9.97  4.23  0.28  4.58]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 2 7 9 0 5 1 6 0 7]
 [9 2 9 5 0 0 9 6 0 9]
 [4 7 3 4 4 1 4 4 0 6]
 [9 8 8 5 8 5 9 2 6 7]
 [8 9 8 2 7 6 0 1 5 0]
 [9 3 6 3 0 0 1 0 0 9]
 [4 0 0 9 3 0 2 7 1 5]
 [1 8 6 4 7 1 3 9 4 1]
 [0 4 6 8 1 5 8 6 9 8]
 [8 4 6 2 6 8 2 1 8 0]]
[[0 0 0 0 0]
 [0 4 2 7 9]
 [0 9 2 9 5]
 [0 4 7 3 4]
 [0 9 8 8 5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z=np.arange(1,15,dtype=np.uint32)
stride_tricks.as_strided(Z,(11,4),(4,4))

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z=np.random.uniform(0,1,(10,10))
U,S,V=np.linalg.svd(Z)
rank=np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
a=np.random.randint(1,10,5)
np.bincount(a).argmax()

7

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z=np.random.randint(0,5,(10,10))
n=3
i=1+(Z.shape[0]-3)
j=1+(Z.shape[1]-3)
C=stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 1 1]
   [2 0 1]
   [0 4 0]]

  [[1 1 4]
   [0 1 3]
   [4 0 3]]

  [[1 4 3]
   [1 3 3]
   [0 3 3]]

  [[4 3 0]
   [3 3 4]
   [3 3 2]]

  [[3 0 1]
   [3 4 4]
   [3 2 1]]

  [[0 1 0]
   [4 4 1]
   [2 1 0]]

  [[1 0 3]
   [4 1 4]
   [1 0 3]]

  [[0 3 3]
   [1 4 4]
   [0 3 1]]]


 [[[2 0 1]
   [0 4 0]
   [1 2 2]]

  [[0 1 3]
   [4 0 3]
   [2 2 0]]

  [[1 3 3]
   [0 3 3]
   [2 0 0]]

  [[3 3 4]
   [3 3 2]
   [0 0 3]]

  [[3 4 4]
   [3 2 1]
   [0 3 3]]

  [[4 4 1]
   [2 1 0]
   [3 3 2]]

  [[4 1 4]
   [1 0 3]
   [3 2 0]]

  [[1 4 4]
   [0 3 1]
   [2 0 2]]]


 [[[0 4 0]
   [1 2 2]
   [3 3 3]]

  [[4 0 3]
   [2 2 0]
   [3 3 1]]

  [[0 3 3]
   [2 0 0]
   [3 1 3]]

  [[3 3 2]
   [0 0 3]
   [1 3 1]]

  [[3 2 1]
   [0 3 3]
   [3 1 4]]

  [[2 1 0]
   [3 3 2]
   [1 4 3]]

  [[1 0 3]
   [3 2 0]
   [4 3 0]]

  [[0 3 1]
   [2 0 2]
   [3 0 3]]]


 [[[1 2 2]
   [3 3 3]
   [4 3 2]]

  [[2 2 0]
   [3 3 1]
   [3 2 3]]

  [[2 0 0]
   [3 1 3]
   [2 3 1]]

  [[0 0 3]
   [1 3 1]
   [3 1 4]]

  [[0 3 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9  4  4 16  1]
 [ 4  2  2  4 10]
 [ 4  2  5 42 12]
 [16  4 42  1  9]
 [ 1 10 12  9  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p,n= 10, 20
M=np.ones((p,n,n))
V=np.ones((p,n,1))
S=np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z=np.ones((16,16))
k=4
S=np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(10): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[95 96 97 98 99]
[96 97 98 99 95]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
z=np.array([("hello",2.5,3),
            ("world",3.6,2)])
r=np.core.records.fromarrays(z.T,names='col1,col2,col3',formats='S8,f8,i8')
print(r)

[(b'hello', 2.5, 3) (b'world', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x=np.random.random(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.74 s per loop
10 loops, best of 5: 138 ms per loop
10 loops, best of 5: 122 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
C=(A[..., np.newaxis, np.newaxis] == B)
rows=np.where(C.any((3,1)).all(1))[0]
print(rows)

[2 3 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z=np.random.randint(0,5,(10,3))
print(Z)
E=np.all(Z[:,1:] == Z[:,:-1], axis=1)
U=Z[~E]
print(U)
U=Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 2 4]
 [1 1 3]
 [3 2 3]
 [1 3 3]
 [4 0 0]
 [0 1 1]
 [4 3 1]
 [1 3 1]
 [4 3 2]
 [3 3 2]]
[[0 2 4]
 [1 1 3]
 [3 2 3]
 [1 3 3]
 [4 0 0]
 [0 1 1]
 [4 3 1]
 [1 3 1]
 [4 3 2]
 [3 3 2]]
[[0 2 4]
 [1 1 3]
 [3 2 3]
 [1 3 3]
 [4 0 0]
 [0 1 1]
 [4 3 1]
 [1 3 1]
 [4 3 2]
 [3 3 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,21(5,5))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.37, 0.13, 0.14, 0.57, 0.72, 0.21, 0.32, 0.07, 0.13, 0.33],
       [0.04, 0.01, 0.01, 0.06, 0.08, 0.02, 0.03, 0.01, 0.01, 0.04],
       [0.17, 0.06, 0.06, 0.27, 0.33, 0.1 , 0.15, 0.03, 0.06, 0.15],
       [0.43, 0.15, 0.16, 0.66, 0.82, 0.24, 0.36, 0.09, 0.15, 0.37],
       [0.06, 0.02, 0.02, 0.09, 0.12, 0.03, 0.05, 0.01, 0.02, 0.05],
       [0.4 , 0.14, 0.15, 0.62, 0.77, 0.23, 0.34, 0.08, 0.14, 0.35],
       [0.04, 0.01, 0.02, 0.06, 0.08, 0.02, 0.04, 0.01, 0.01, 0.04],
       [0.18, 0.07, 0.07, 0.29, 0.36, 0.11, 0.16, 0.04, 0.07, 0.16],
       [0.05, 0.02, 0.02, 0.09, 0.11, 0.03, 0.05, 0.01, 0.02, 0.05],
       [0.24, 0.09, 0.09, 0.37, 0.46, 0.13, 0.2 , 0.05, 0.09, 0.21]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X=np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n=4
M=np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M&=(X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X=np.random.randn(100) 
N=1000 
idx=np.random.randint(0, X.size, (N, X.size))
means=X[idx].mean(axis=1)
confint=np.percentile(means, [2.5, 97.5])
print(confint)

[-0.21  0.14]
